### ISSUE TITLE
Usability testing

### ISSUE THREAD

**Issue by Deele** [yiisoft-contrib/yiiframework.com#115]
Currently, I see many problems in landing page, and in other pages I have seen, but I will not report them, because I am not informed about project, to understand its purpose. To create great project and to sell Yii in the best way possible, Yii website usability testing should be done.

We need either to hire someone with experience, or do that by ourselves.

Anyway, it would be required to answer questions similar to: what is purpose of the site, how do you/we want Yii framework site to be used, what message should user receive while using it, etc.

Issue on the same topic #22

**Comment by jacmoe** [comment]
And.. ?
I think it would be more productive to create specific and focused issues - would be far more helpful IMO.

**Comment by Deele** [comment]
It will not be productive to invest energy in testing an item, that has unknown purpose. I would like to see answers to those quests, to better understand it. Sometimes, you just have to leave that one button, icon, image, page, just because it is required to serve page/site/project/company/ideology purpose. Do you think that we all already know reasoning behind those decisions that are already made? I don't think that I need to "throw out work of someone", just because I have other opinion. Behind every detail in website, there should be a reasoning, someone is responsible for current design draft. I just hope that this draft has more background than plain idea out of thin air from mind of Сергей Хильков (Eshill). There should be some sort of specification, site structure graph, something that serves as backbone to this project.

**Comment by jacmoe** [comment]
I want you to understand that this project has a very clear goal: to replace the current website of Yii framework.
It does not get any more concrete than that, because that is actually fairly specific.

Sergei might be our designer, but he is working within the constraints set up by this project.

Don't expect a corporate design draft.
This is not a software application - it is a replacement of yiiframework.com :)

If there is anything in particular that you think needs to be improved / changed / whatever, create an issue about it and discuss it.

**Comment by Deele** [comment]
OK, you do not have answers to those questions, I will try to be more precise.

Yes, I understand that it is replacement of current site. Why did it need replacement at first place?

No offense, I am confused because of lack of knowledge about project. Do you have something against corporate design drafts? I expect professionalism and serious approach to web project development. IMHO, if you want community to really help Yii framework to grow (if that is the goal), then *core team* should be open to such questions. I want to help, but it makes sense for me to invest energy in something, that is really going to make a difference. Plain redesign(-branding) should not be done with serious reasons. If changes in the site won't increase the value of project (or achieve any other goal, that is still unknown), why those changes should be introduced at all, why should someone work just to... work, just to spend energy/focus/time.

**Comment by jacmoe** [comment]
I don't mean to be brash, but have you actually visited [Yii Framework](http://www.yiiframework.com/) ?

If you have, you will probably agree with me that it does not sell Yii very well.

This project is the result of discussions between the Yii team members, and a couple of months ago I pitched in because I wasn't very happy with the state of the Yii site.

We have gone through several mockups/designs, and we are now in a the final phase, having decided to use the design proposed by @eshill.

We have had a lot of discussions, etc - and now is not the time to sit down and talk - simply because the project is in a advanced stage. :)

The open issues will give you an impression of where the project is at - and if you are curious, check out the first posts in Yii forum - Misc - Yii site.

**Comment by cebe** [comment]
A new website is needed because Yii has grown a lot since the last site has been created.
The goal of this project is to replace the old site with the following main goals:

- attract new users by providing better start and guidance.
- provide better and faster access to documentation.
- create a place for the community to evolve in one place.

The first one is nearly not provided by the current site. For Yii2 there is basically no entry.
Yii 1 and Yii 2 have different docs in completely separate parts of the site.
Currently community is split into stackoverflow, IRC, forum, github. The new site should integrate these channels to bring them all together to some extend.

We write this on a new base because changing the old site to intregrate all new things would be much harder than starting from scratch.

**Comment by jacmoe** [comment]
One of my main complaints about the current site is indeed the documentation - I think we have done a great job improving it.

I agree with @cebe that the current site really is not a reflection of where the project is at now, and that we should try to gather the community around the project much better - it is too fragmented at the moment, I think.

**Comment by Deele** [comment]
@jacmoe Why is it bad time to sit down and talk? I think, the closer you are to the finish of project, the more confident you should be about it.

@cebe Thank you - that is kind of answer I expected. Can you be more elaborate how each of those goals will be achieved?

**Comment by cebe** [comment]
> @cebe Thank you - that is kind of answer I expected. Can you be more elaborate how each of those goals will be achieved?

I think it is a good idea to write down these goals. Will do that later when I have more time to focus.

**Comment by jacmoe** [comment]
> Why is it bad time to sit down and talk? I think, the closer you are to the finish of project, the more confident you should be about it.

I think we misunderstood each other @Deele :)

I think it is useful to have a conversation about this, because it makes us vocal about it. It is useful.
To some extent.

**Comment by jacmoe** [comment]
> OK, you do not have answers to those questions, I will try to be more precise.

It is not that I don't have answers, I just can't be bothered to write them down for you, right here and right now, because I don't have the time to do so, I don't see the point in doing so, and because you could be doing it instead of me :)

**Comment by samdark** [comment]
Closing since it's a meta-issue...
