### ISSUE TITLE
Responsive: Add another big size to allow more space for docs

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#210]
from the chat:

> @nadar Today at 10:38 AM in #general
regarding the new website: why not using the full container width in order to display guide and api informations (http://yiiframework.domain-na.me/doc/guide/2.0/en/start-forms) ? there is plenty of space. Then the guide/api navigation could be larger and would not look that “compressed”.

> @cebe < 1 minute ago
could definitively use a bit more space if screen is big enough. we currently use bootstraps default sizes, we could add another one for big screens.

**Comment by samdark** [comment]
Not sure it's a good idea. According to many UX researchers text is more readable when there's certain max number of characters per line.

- https://baymard.com/blog/line-length-readability
- http://webtypography.net/2.1.2

**Comment by cebe** [comment]
lets keep the text width then, but expand the nav more.

**Comment by indeveler** [comment]
I'm not sure if I should create new issue. 
I have no big screen but if I scale the page in browser I see this (resolution 1920): 
![image](https://user-images.githubusercontent.com/1275668/29879928-adf4c0f0-8dd0-11e7-9881-5e3b7bb08981.png)

I'm not sure if it is good idea to keep #scrollnav in .visible-huge.fixed div. This is what happens if we wrap it in a div with "position: absolute" and make it "position: fixed" and insert it into .container:
![image](https://user-images.githubusercontent.com/1275668/29880256-847733ba-8dd1-11e7-8aaa-f3d4318779e7.png)

**Comment by indeveler** [comment]
Should I make pull-request with this updates?

**Comment by samdark** [comment]
Yes, it looks better with these changes.

**Comment by Eseperio** [comment]
Please note that also the sidenav is too thin. Content keeps readable with 1 column less. Codemirror should have line wrap disabled.
