### ISSUE TITLE
There are two equals html IDs

### ISSUE THREAD

**Issue by Eseperio** [yiisoft-contrib/yiiframework.com#220]
Main search box and wiki sidebar search box have the same id. This is not allowed in html. 
The same happens in extensions page..

**Comment by cebe** [comment]
yeah, there will be only one search box once search implementation is finished. Thanks for reporting!

**Comment by Eseperio** [comment]
I think leaving only one search box is not the best solution for customer, sometimes you need search box for only a certain type of items, like extensions and wiki. 
Let me a few days and i´ll show you what i´m talking about.

**Comment by Eseperio** [comment]
Don´t wait, here is a sample:
![image](https://user-images.githubusercontent.com/5459366/30244344-6bb771a8-95bc-11e7-91a1-45b3122ea160.png)

**Comment by cebe** [comment]
My idea of the implementation of the search was that the main search box will adjust its context based on which site you are on. i..e if you are inside of extensions, search will show extensions only by default and lets you change scope by clicking on buttons or tabs.

**Comment by Eseperio** [comment]
It´s a good idea, but only those who use it at least one time will know what it does. My experience in ecommerce taught me that you need to do the things "dumb proof". That means don´t expect a user to know your search box will change automatically depending on page, put a search box just in front of his eyes.

**Comment by jacmoe** [comment]
I have a better idea (I hope) : 

Change the input box placeholder text accordingly.

For instance, when the page is wiki, the placeholder would be "Search the wiki..."

**Comment by jacmoe** [comment]
We can't compare the Yii online documentation with a commerce site because it is two very different scenarios.

Do we really want to waste valuable space? That could otherwise be used to display the actual content?

No, I don't think so.
The problem with the current wiki, is that space is limited, making it harder to really read and digest the material.

And developing the new docs/wiki interface has taught me, that space is extremely valuable and scarce: each and every pixel is important.

Commerce sites has to deal with casual users whose attention span is limited and the goal is to make them take actions that will lead to sale.

Our goal is very different: to maximise learning - and a huge search box at the top of each page is totally not conducive towards that goal, IMO!

**Comment by rob006** [comment]
> Our goal is very different: to maximise learning - and a huge search box at the top of each page is totally not conducive towards that goal, IMO!

This box should not be on every page but on index pages. If I go to wiki articles list or extensions list, the first thing I want to do is search something, because it is very doubtful that I will find what I am looking for on the first page of results. IMO it is worth to "sacrifice" some space for such important element in these views.

Also note that on mobiles search in menu is hidden and there is no easy and intuitive way to search something on phone.

**Comment by jacmoe** [comment]
Did @Eseperio say that the intention was to only put the search hero on the index page? (He didn't).

But, in that case, I can live with it (I think).

**Comment by Eseperio** [comment]
@jacmoe But yes, a big search hero must be on index page, in others page should be a small hero.

**Comment by jacmoe** [comment]
Could that wiki search be in the sidebar when not on the index page?

That would be better, so that the content area doesn't get smaller.

**Comment by cebe** [comment]
I made the search context aware in 9077135, its not perfect from a design perspective but we can improve that after launsh.
