### ISSUE TITLE
Search Engine Link broken

### ISSUE THREAD

**Issue by buttflattery** [yiisoft-contrib/yiiframework.com#396]
If you type in google 

`yii2 types of widgets`

on search results the third result lands on a `404 error ` on yii site, which is pointing to the link `https://www.yiiframework.com/extension/yiisoft/yii2-bootstrap/doc/api/2.2/yii-bootstrap-widget`

See image below

![image](https://user-images.githubusercontent.com/1536454/45325520-83f78e00-b56a-11e8-802d-c00747ab25b1.png)

**Comment by cebe** [comment]
I found out that there was a 2.2 branch for bootstrap, which has been in development for some time but then has been removed. That is why the URLs have been indexed by google.

I have updated the 404 pages so that you can now choose another version in case the page does not exist.

fixed by #397.

Thanks for reporting!
