### ISSUE TITLE
Add a "got to top" arrow

### ISSUE THREAD

**Issue by cebe** [yiisoft-contrib/yiiframework.com#45]
it should be available as soon as you scroll down and bring you back to the top.

should remove the top button from apidoc then.

**Comment by jacmoe** [comment]
I added the useless feature already :)

Twice, to be exact, because I fixed the go to top in the guide.

I am using it because most of the time, the HOME key is too far away.
Because when I want to use it, my mouse hand is busy navigating. And the only time that HOME is closer would be if I navigated Emacs style by using my keyboard. Personally, especially on content heavy pages, I wish it were there if it wasn't.
